spring:
  datasource:
    url: jdbc:postgresql://localhost:5401/account-info-backend
    username: account-info-backend
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: 'false'
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  liquibase:
    change-log: classpath:domain/changelog-master.yml
    drop-first: false
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    http-statuses:
      org.springframework.security.authorization.AuthorizationDeniedException: unauthorized
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
springdoc:
  pathsToMatch: /, /api/**
server:
  error:
    include-message: never
    include-stacktrace: never
  port : 8051
